from pydantic import BaseModel, Field
from typing import List

class AnswerChunk(BaseModel):
    """
    Represents a single retrieved chunk from the database.
    """
    chunk_text: str = Field(..., description="Text content of the chunk")
    document_name: str = Field(..., description="Original document name")
    category: str = Field(..., description="Category of the document chunk")
    similarity_score: float = Field(..., description="Optional similarity score from vector search")

class AnswerGenerateResponse(BaseModel):
    """
    Represents the final answer generated by the RAG system, along with the top-K chunks retrieved.
    """
    answer: str = Field(..., description="Answer generated by the LLM")
    retrieved_chunks: List[AnswerChunk] = Field(
        ..., description="Top-K relevant chunks used to generate the answer"
    )
