from pydantic import BaseModel, Field
from uuid import UUID
from typing import Optional

class ChatRequest(BaseModel):
    message: Optional[str] = Field(None, description="The user's question or prompt")
    top_k: int = Field(5, description="Number of top document chunks to retrieve")
    company_id: UUID = Field(..., description="The ID of the company to scope the search")
    type: str = Field(..., description='voice || text')  # Fixed: removed comma
    audio_url: Optional[str] = Field(None)

class ChatResponse(BaseModel):
    answer: Optional[str] = Field(None, description="The answer generated by the RAG system")
    role: str = Field(..., description='assistant')  # Fixed: removed comma
    type: str = Field(..., description='voice || text')  # Fixed: removed comma
    audio_url: Optional[str] = Field(None)
    duration: Optional[float] = None