"""update company table

Revision ID: b8d2f199841f
Revises: 07491d2e5e2c
Create Date: 2026-03-01 05:37:59.285873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8d2f199841f'
down_revision: Union[str, Sequence[str], None] = '07491d2e5e2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('email', sa.String(), nullable=False))
    op.add_column('companies', sa.Column('status', sa.Enum('Active', 'Inactive', name='companystatus'), nullable=False))
    op.add_column('companies', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'companies', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='unique')
    op.drop_column('companies', 'updated_at')
    op.drop_column('companies', 'status')
    op.drop_column('companies', 'email')
    # ### end Alembic commands ###
