from fastapi import APIRouter, HTTPException, status, Depends
from sqlalchemy.orm import Session,joinedload

from App.models.model import VisitorSession, VisitorMessage
from App.schemas.chat import ChatRequest, ChatResponse,MessageHistoryResponse,SessionListItem,MessageSchema
from App.services.chat_service import generate_answer
from App.services.voice_service import process_voice_cloud, generate_voice_cloud
from datetime import datetime
from App.database.connection import SessionLocal
import uuid
from typing import List
from App.services.dependencies import require_company_admin 
import logging


from sqlalchemy import select, desc


logger = logging.getLogger(__name__)
def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
router = APIRouter()

@router.post("/", response_model=ChatResponse)
async def chat_endpoint(request: ChatRequest, db: Session = Depends(get_db)): 
    
    if not request.company_id:
        raise HTTPException(status_code=400, detail="company_id is required")

    try:
        # 1. UPSERT SESSION: Use the ID generated by the frontend
        # We try to convert the string ID to a UUID object to match your model
        try:
            frontend_session_id = uuid.UUID(request.session_id)
        except ValueError:
            raise HTTPException(status_code=400, detail="Invalid session_id format")

        session = db.query(VisitorSession).filter(VisitorSession.id == frontend_session_id).first()
        
        if not session:
            # Create new session if it doesn't exist
            session = VisitorSession(
                id=frontend_session_id, 
                company_id=request.company_id
            )
            db.add(session)
        else:
            # Update last active timestamp
            session.last_active = datetime.utcnow()

        db.commit() # Ensure session exists before adding messages

        # --- PREPARE DATA ---
        user_message_content = ""
        user_file_metadata = None
        ai_answer = ""
        voice_url, duration = None, None

        # --- CASE 1: TEXT ---
        if request.type == 'text':
            user_message_content = request.message
            ai_answer = generate_answer(
                question=request.message,
                top_k=request.top_k,
                company_id=request.company_id
            )

        # --- CASE 2: VOICE ---
        elif request.type == 'voice':
            # Save the incoming voice URL in metadata
            user_file_metadata = {"media_url": request.audio_url, "type": "voice_note"}
            
            # STT: Convert user voice to text
            user_text, lang_code = await process_voice_cloud(request.audio_url)
            user_message_content = user_text or "Audio Message"
            
            # AI Logic
            ai_answer = generate_answer(
                question=user_message_content,
                top_k=request.top_k,
                company_id=request.company_id
            )

            # TTS: Convert AI answer back to voice
            if ai_answer:
                voice_url, duration = await generate_voice_cloud(ai_answer, lang_code)

        # 2. PERSIST MESSAGES
        # Store User Message
        user_msg = VisitorMessage(
            session_id=session.id,
            role="visitor",
            content=user_message_content,
            file_=user_file_metadata
        )
        db.add(user_msg)

        # Store AI Assistant Message
        assistant_msg = VisitorMessage(
            session_id=session.id,
            role="assistant",
            content=ai_answer,
            file_={"media_url": voice_url, "duration": duration} if voice_url else None
        )
        db.add(assistant_msg)
        
        db.commit() # Save both messages to history

        return ChatResponse(
            answer=ai_answer,
            audio_url=voice_url,
            type=request.type,
            role='assistant',
            duration=duration
        )

    except Exception as e:
        db.rollback() # Important: undo changes if something fails
        print(f"Chat storage error: {e}") 
        raise HTTPException(status_code=500, detail="Error processing and storing chat")

from fastapi import Query, HTTPException, status
from typing import Optional

@router.get("/history/{session_id}", response_model=List[MessageHistoryResponse])
async def get_chat_history(
    session_id: str, 
    # Use Query(None) to make it optional to the validator, but required by your logic
    company_id: Optional[str] = Query(None), 
    db: Session = Depends(get_db)
):
    # 1. Immediate validation with a clear error message
    if not company_id:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Missing required query parameter: company_id"
        )

    try:
        uid = uuid.UUID(session_id)
    except ValueError:
        raise HTTPException(status_code=400, detail="Invalid session_id format")

    try:
        # 2. Secure Query using JOIN
        messages = (
            db.query(VisitorMessage)
            .join(VisitorSession, VisitorMessage.session_id == VisitorSession.id)
            .filter(
                VisitorMessage.session_id == uid,
                VisitorSession.company_id == company_id
            )
            .order_by(VisitorMessage.created_at.asc())
            .all()
        )

        # 3. Handle specific Auth scenarios
        if not messages:
            session = db.query(VisitorSession).filter(VisitorSession.id == uid).first()
            if session and str(session.company_id) != company_id:
                raise HTTPException(
                    status_code=status.HTTP_403_FORBIDDEN, 
                    detail="Access denied: Session belongs to a different company."
                )

        return [
            {
                "role": msg.role,
                "text": msg.content,
                "audio": msg.file_.get("media_url") if msg.file_ else None
            }
            for msg in messages
        ]

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"History Fetch Error: {str(e)}")
        raise HTTPException(status_code=500, detail="Internal server error")



@router.get("/sessions", response_model=List[SessionListItem])
async def get_all_sessions(
    db: Session = Depends(get_db), 
    admin: dict = Depends(require_company_admin)
):
    company_id = admin.get("company_id")
    
    if not company_id:
        raise HTTPException(status_code=400, detail="Admin profile missing company association")

    try:
        # Fetch sessions ordered by last_active
        sessions = db.query(VisitorSession)\
            .options(joinedload(VisitorSession.messages))\
            .filter(VisitorSession.company_id == company_id)\
            .order_by(desc(VisitorSession.last_active))\
            .all()

        return [
            {
                "id": str(s.id), # Ensure UUID is a string
                "updated_at": s.last_active.isoformat() if s.last_active else None,
                # Logic to handle if the last message was text or audio
                "last_message": (
                    s.messages[-1].content if s.messages and s.messages[-1].content 
                    else "🎤 Voice Note" if s.messages and s.messages[-1].file_ 
                    else "No messages yet"
                )
            } for s in sessions
        ]
    except Exception as e:
        logger.error(f"Failed to fetch sessions: {str(e)}")
        raise HTTPException(status_code=500, detail="Internal Server Error")

@router.get("/history/admin/{session_id}", response_model=List[MessageSchema])
async def get_chat_history(
    session_id: str, 
    db: Session = Depends(get_db),
    admin: dict = Depends(require_company_admin) # Keep it protected
):
    try:
        # Convert string to UUID if your DB uses UUID type
        messages = db.query(VisitorMessage)\
            .filter(VisitorMessage.session_id == session_id)\
            .order_by(VisitorMessage.created_at.asc())\
            .all()
        for m in messages:
           print(m.__dict__)
        if not messages and not db.query(VisitorSession).filter(VisitorSession.id == session_id).first():
             raise HTTPException(status_code=404, detail="Session not found")
       
        return [
            {   "id":m.id,
                "role": m.role,
                "text": m.content,
                "audio": m.file_.get("media_url") if m.file_ else None,
                "created_at": m.created_at
            } for m in messages
           
        ]
    except HTTPException as he:
        raise he
    except Exception as e:
        logger.error(f"Error fetching history for {session_id}: {str(e)}")
        raise HTTPException(status_code=500, detail="Internal Server Error")
@router.patch("/message/{message_id}")
async def edit_message(
    message_id: str, 
    payload: dict, 
    db: Session = Depends(get_db),
    admin: dict = Depends(require_company_admin) # Get admin info
):
    # 1. Fetch message AND check company ownership in one go
    msg = db.query(VisitorMessage).join(VisitorSession).filter(
        VisitorMessage.id == message_id,
        VisitorSession.company_id == admin.get("company_id") # Security Lock
    ).first()

    if not msg:
        # We return 404 even if it exists but belongs to another company 
        # to prevent "ID probing"
        raise HTTPException(status_code=404, detail="Message not found or unauthorized")
    
    new_text = payload.get("text")
    if not new_text:
        raise HTTPException(status_code=400, detail="Content cannot be empty")

    msg.content = new_text
    msg.is_edited = True 
    
    # Update the parent session's last_active so it stays at the top
    msg.session.last_active = datetime.utcnow()
    
    db.commit()
    return {"status": "updated", "message_id": message_id}
@router.post("/send-admin")
async def send_admin_message(
    request: dict, 
    db: Session = Depends(get_db),
    admin: dict = Depends(require_company_admin)
):
    session_id = request.get("session_id")
    admin_company_id = admin.get("company_id")

    # 1. Verify the session belongs to this admin's company
    session = db.query(VisitorSession).filter(
        VisitorSession.id == session_id,
        VisitorSession.company_id == admin_company_id
    ).first()

    if not session:
        raise HTTPException(status_code=403, detail="Unauthorized: Session belongs to another company")

    # 2. Create the manual message
    admin_msg = VisitorMessage(
        session_id=session_id,
        role="assistant", 
        content=request.get("text")
    )
    
    # 3. Update session timestamp for the sidebar "sort by recent" logic
    session.last_active = datetime.utcnow()
    
    db.add(admin_msg)
    db.commit()
    
    return {"status": "sent", "timestamp": session.last_active}