import uuid
from datetime import datetime
from sqlalchemy import Column, String, Text, Boolean, ForeignKey, DateTime, JSON,Enum
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from pgvector.sqlalchemy import Vector
from App.database.connection import Base
import enum
class CompanyStatus(enum.Enum):
    Active = "Active"
    Inactive = "Inactive"
class Company(Base):
    __tablename__ = "companies"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    name = Column(String, unique=True, nullable=False)
    email = Column(String, unique=True, nullable=False)
    
    # Corrected Status Column
    status = Column(Enum(CompanyStatus), default=CompanyStatus.Active, nullable=False)
    
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    users = relationship("User", back_populates="company", cascade="all, delete-orphan")
    documents = relationship("Document", back_populates="company", cascade="all, delete-orphan")
    chunks = relationship("DocumentChunk", back_populates="company", cascade="all, delete-orphan")


class User(Base):
    __tablename__ = "users"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    email = Column(String, unique=True, index=True, nullable=False)
    password_hash = Column(String, nullable=False)
    role = Column(String)  # e.g., "SYSTEM_ADMIN", "COMPANY_ADMIN"
    is_active = Column(Boolean, default=True)
    
    company_id = Column(UUID(as_uuid=True), ForeignKey("companies.id"), nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    # Relationships
    company = relationship("Company", back_populates="users")


class Document(Base):
    __tablename__ = "documents"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    company_id = Column(UUID(as_uuid=True), ForeignKey("companies.id"), nullable=False)
    
    category = Column(String, index=True)
    document_name = Column(String, nullable=False)
    document_version = Column(String, default="v1")
    
    # Cloudinary/File storage metadata
    file_metadata = Column(JSON)  # Stores {"public_id": "...", "media_url": "..."}
    
    created_at = Column(DateTime, default=datetime.utcnow)
    creator_id = Column(UUID(as_uuid=True), ForeignKey("users.id"))

    # Relationships
    company = relationship("Company", back_populates="documents")
    chunks = relationship("DocumentChunk", back_populates="document", cascade="all, delete-orphan")


class DocumentChunk(Base):
    __tablename__ = "document_chunks"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    document_id = Column(UUID(as_uuid=True), ForeignKey("documents.id"), nullable=False)
    company_id = Column(UUID(as_uuid=True), ForeignKey("companies.id"), nullable=False)
    chunk_text = Column(Text, nullable=False)
    
    embedding = Column(Vector(768))  

    # Relationships
    document = relationship("Document", back_populates="chunks")
    company = relationship("Company", back_populates="chunks")
    import uuid
from datetime import datetime
from sqlalchemy import Column, String, Text, ForeignKey, DateTime
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from App.database.connection import Base

class VisitorSession(Base):
    __tablename__ = "visitor_sessions"

    # The unique ID generated by the Mobile App
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    
    
    company_id = Column(UUID(as_uuid=True), ForeignKey("companies.id"), nullable=False)
    
    created_at = Column(DateTime, default=datetime.utcnow)
    last_active = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationship to messages
    messages = relationship("VisitorMessage", back_populates="session", cascade="all, delete-orphan")

class VisitorMessage(Base):
    __tablename__ = "visitor_messages"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    session_id = Column(UUID(as_uuid=True), ForeignKey("visitor_sessions.id"), nullable=False)
    
    role = Column(String, nullable=False)  # "visitor" or "assistant"
    content = Column(Text, nullable=True)
    
    # If the visitor sent a voice note, store the Cloudinary URL here
    file_ = Column(JSON, nullable=True) # Stores {"public_id": "...", "media_url": "..."}
    
    created_at = Column(DateTime, default=datetime.utcnow)

    session = relationship("VisitorSession", back_populates="messages")